-- Formats.SDCC.Opt (decl)
--
-- Options for handling Small Device C Compiler (SDCC) files.
--
-- Author: Niklas Holsti, Tidorum Ltd, 2007.
--
-- A component of the Bound-T Worst-Case Execution Time Tool.
--
-------------------------------------------------------------------------------
-- Copyright (c) 1999 .. 2015 Tidorum Ltd
-- All rights reserved.
--
-- Redistribution and use in source and binary forms, with or without
-- modification, are permitted provided that the following conditions are met:
--
-- 1. Redistributions of source code must retain the above copyright notice, this
--    list of conditions and the following disclaimer.
-- 2. Redistributions in binary form must reproduce the above copyright notice,
--    this list of conditions and the following disclaimer in the documentation
--    and/or other materials provided with the distribution.
--
-- This software is provided by the copyright holders and contributors "as is" and
-- any express or implied warranties, including, but not limited to, the implied
-- warranties of merchantability and fitness for a particular purpose are
-- disclaimed. In no event shall the copyright owner or contributors be liable for
-- any direct, indirect, incidental, special, exemplary, or consequential damages
-- (including, but not limited to, procurement of substitute goods or services;
-- loss of use, data, or profits; or business interruption) however caused and
-- on any theory of liability, whether in contract, strict liability, or tort
-- (including negligence or otherwise) arising in any way out of the use of this
-- software, even if advised of the possibility of such damage.
--
-- Other modules (files) of this software composition should contain their
-- own copyright statements, which may have different copyright and usage
-- conditions. The above conditions apply to this file.
-------------------------------------------------------------------------------
--
-- $Revision: 1.5 $
-- $Date: 2015/10/24 20:53:54 $
--
-- $Log: formats-sdcc-opt.ads,v $
-- Revision 1.5  2015/10/24 20:53:54  niklas
-- Moved to free licence.
--
-- Revision 1.4  2012-01-21 11:58:33  niklas
-- Options are aliased, for BT-CH-0225.
--
-- Revision 1.3  2009-12-07 11:06:06  niklas
-- BT-CH-0184: Arithmetic.Value_T replaces Processor.Value_T.
--
-- Revision 1.2  2007/10/07 19:25:00  niklas
-- Added Assume_Ext_RAM_U8 and Warn_Assumed_Type_Loc.
--
-- Revision 1.1  2007/09/22 14:19:25  niklas
-- First version.
--


package Formats.SDCC.Opt is


   -- Some option variables are "aliased" so that they can be referenced
   -- from the Bound-T option tables.


   Deallocate : Boolean := True;
   --
   -- Whether to use Unchecked_Deallocation to release unused heap
   -- memory.


   Trace_Loading : Boolean := False;
   --
   -- Whether to trace on standard output the process of accessing
   -- and interpreting CDB information.


   Default_Assume_Ext_RAM_U8 : constant Boolean := True;
   --
   -- Default value for Assume_Ext_RAM_U8, below.


   Assume_Ext_RAM_U8 : aliased Boolean := Default_Assume_Ext_RAM_U8;
   --
   -- Whether to assume, for a CDB symbol with a Linker record but no
   -- compiler record and thus no type/size info, an unsigned 8-bit
   -- type and a location in External RAM.


   Default_Warn_Assumed_Type_Loc : constant Boolean := False;
   --
   -- Default value for Warn_Assumed_Type_Loc, below.


   Warn_Assumed_Type_Loc : aliased Boolean := Default_Warn_Assumed_Type_Loc;
   --
   -- Whether to issue a warning when the CDB parser assumes a certain
   -- type and location (memory space) for a CDB symbol that has a Linker
   -- record but no compiler record.


   Default_Assembler_Lines : constant Boolean := False;
   --
   -- Default value for Assembler_Lines below.


   Assembler_Lines : aliased Boolean := Default_Assembler_Lines;
   --
   -- Whether to include the source-line/code-address connnections
   -- generated by the assembler, while loading symbolic debugging
   -- information from a CDB file.
   --
   -- The default SDCC options seem to make the assembler generate
   -- such source-line connections even while assembling code that
   -- stems from a C source file, which can lead to confusing "Also"
   -- lines in Bound-T output.


end Formats.SDCC.Opt;
